package com.hackathon.model.enums;

public enum AuditEventType {
    CUSTOMER_REQUEST,
    PRODUCT_SEARCH,
    PRODUCT_RECOMMENDATION,
    UPSELL_SUGGESTED,
    PRODUCT_ADDED,
    PRODUCT_REMOVED,
    CART_CALCULATED,
    CHECKOUT_PROPOSED,
    CUSTOMER_CONFIRMATION,
    PAYMENT_SAFETY_CHECK,
    PAYMENT_REQUESTED,
    PAYMENT_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_RETRY,
    PRICE_TAMPERING_ATTEMPT
}